name: "Clean Markdown"
description: "Formats markdown files and adds table of contents"
author: "Gopal Sharma <gps@surya-soft.com>"
inputs:
  commit_message:
    description: Commit message
    required: true
  gh_token:
    description: GitHub Token
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: arrow-down
  color: red
